### ISSUE TITLE
no link to the API

### ISSUE THREAD

**Issue by f18m** [zeromq/zeromq.org#10]
New website contains a direct link to the ZMQ guide but no direct link to the following page:
    http://api.zeromq.org/
 which I find very useful.
I also think is useful to have that page with some SEO to get on top of google searchs.
Currently I think it's mostly the documentation for ZMQ 2.1 or 3.2 that appear the most frequently out of google searchs but that gives a bit a sense of "outdated" to me...

**Comment by somdoron** [comment]
There is a link over here:

https://zeromq.org/languages/c/

But you are right, we need to put it in a better place, I will add something.

**Comment by somdoron** [comment]
@f18m check the link on the navigation tree on the left side:

https://zeromq.org/get-started/

**Comment by f18m** [comment]
Thanks for the link! 
I just wonder why it opens a page on the 4.2.2 API instead of the "master" version... do you know why perhaps (it's not related to the new website I guess though)

**Comment by somdoron** [comment]
@bluca @sappo any clue why api.zeromq.org is defaulted to version 4.2.2?

**Comment by bluca** [comment]
no idea sorry

**Comment by sappo** [comment]
My guess is that there is a setting in the wikidot admin panel.

Luca Boccassi <notifications@github.com> schrieb am Di., 13. Aug. 2019,
22:11:

**Comment by bluca** [comment]
> My guess is that there is a setting in the wikidot admin panel.

Bingo:

Default start page 4-2:_start

Change to master:_start
