### ISSUE TITLE
All Windows download links https://zeromq.org/download/ are broken due to bintray sunset 

### ISSUE THREAD

**Issue by jcaselman** [zeromq/zeromq.org#112]
For example, the VS15 x64 build link https://dl.bintray.com/zeromq/generic/libzmq-v141-x64-4_3_2.zip returns 403/Forbidden

More details about the sunset here: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by f18m** [comment]
I think all links to bintray have already been removed, this could probably be closed...
