### ISSUE TITLE
Incorrect czmq "Hello world" server example at https://zeromq.org/get-started/

### ISSUE THREAD

**Issue by pstadelmann** [zeromq/zeromq.org#115]
Hi,

The C --> czmq server sample code at https://zeromq.org/get-started/ is incorrect. The error is at line 8-9:
```
int rc = zsock_bind (responder, "tcp://*:5555");
assert (rc == 0);
```
As per the doc, zsock_bind does not return 0 for tcp:// endpoints but the actual port number.
```
// On success, returns the actual port number used, for tcp:// endpoints,
//  and 0 for other transports.
```
Indeed, in the example, the returned value is 5555.

P.

**Comment by bluca** [comment]
the source is at https://github.com/zeromq/zeromq.org/blob/master/content/docs/examples/c/czmq/hello_world_server.md - could you please send a PR to fix it?
