### ISSUE TITLE
Missing "nginx.conf" for Docker

### ISSUE THREAD

**Issue by aviallon** [zeromq/zeromq.org#125]
Building the Dockerfile fails because nginx configuration is missing from the repo

**Comment by f18m** [comment]
I hit this same issue as well, while trying to contribute a doc improvement to the website...

**Comment by sappo** [comment]
The Dockerfile is 4 years old. It would be great if you can have a look at the hugo docs at how it is done now and then send a PR 👍

**Comment by f18m** [comment]
Please note that the PR https://github.com/zeromq/zeromq.org/pull/141 will fix this issue "indirectly": i.e. updating the Dockerfile to some version that does not require nginx.conf at all... 

Long story short: apparently there were several changes in the last few years on the maintainer of the "official" docker image for hugo. According to https://discourse.gohugo.io/t/the-up-to-date-hugo-docker-images/43293   the most updated docker image is now https://hugomods.com/en/docs/docker/.

**Comment by f18m** [comment]
@bluca now that #141 was merged, this can be closed, thanks
