### ISSUE TITLE
api.zeromq.org doesn't use HTTPS

### ISSUE THREAD

**Issue by aagor** [zeromq/zeromq.org#131]
[api.zeromq.org](http://api.zeromq.org) is the only ZeroMQ website (at least from what I know), that doesn't use HTTPS. Is there a reason? Can it be fixed?

**Comment by ethindp** [comment]
It can be fixed. There's no reason it should continue using HTTP. I'd strongly encourage the use of HSTS to resolve this problem.

**Comment by sappo** [comment]
@ethindp I'm not familiar with hsts. How does it work?

**Comment by aagor** [comment]
@sappo It's an extra header, that tells the client to only access the website via HTTPS in the future. This is important to prevent downgrade attacks to HTTP. See more details for example here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security.
But before HSTS can be used, we first need HTTPS...

**Comment by ethindp** [comment]
HSTS shouldn't be all that hard... All that needs doing is letsencrypt integration and your good to go. Then you just add the HSTS header and tell Google that your using it so all the major browser vendors can add it to their internal HSTS list so that it becomes impossible to visit the domain via HTTP thereafter (a good thing IMO).

**Comment by bluca** [comment]
wikidot does not support https. If someone volunteers to migrate all the content of wikidot to github wiki or so, please go ahead and do so.

**Comment by ethindp** [comment]
@bluca It does, if [this blog post](https://blog.wikidot.com/blog:armor-your-wiki-with-a-ssl-certificate) is any indicator (assuming I got the right website). I'm kinda curious why GH pages or something similar isn't being used already, or why a custom VPS isn't being used, but eh.

**Comment by bluca** [comment]
No it doesn't, because it's a dead project. And GH are not used because nobody did the work or paid to get the work done. Are you volunteering?

**Comment by f18m** [comment]
Please note that https://github.com/zeromq/libzmq/pull/4607 would be a first step in moving away from wikidot, by publishing the API docs for libzmq "master" to Github Pages.

**Comment by f18m** [comment]
I think this ticket can now be closed: api.zeromq.org is now a redirect to the https://zeromq.readthedocs.io/en/latest/  website which is over HTTPs
