### ISSUE TITLE
wiki.zeromq.org blog defaced

### ISSUE THREAD

**Issue by sebosp** [zeromq/zeromq.org#139]
I was going through some stackoverflow links regarding uses of zeromq, one of them pointed to the blog about recent references/uses of zeromq:

http://wiki.zeromq.org/blog:_start

This contains information about epoxy products in indonesian 
![image](https://github.com/zeromq/zeromq.org/assets/873436/b32dd93d-5e77-4618-8cd4-22813f2cd9f1)

There are whatsapp links and shortened links as well so potential phishing/scam.

The edit link is broken as well.

**Comment by sappo** [comment]
Thanks for bringing this to our attention.

Reverted the changes
