### ISSUE TITLE
Links to OBS package builds seem pretty old

### ISSUE THREAD

**Issue by f18m** [zeromq/zeromq.org#142]
At this page https://zeromq.org/download/ I can see that:
* libzmq appears 1yr old using the link  https://build.opensuse.org/project/show/network:messaging:zeromq:git-stable
* libzmq appears 2yr old using the link  https://build.opensuse.org/project/show/network:messaging:zeromq:git-draft
* libzmq appears quite new (16d old) looking at https://build.opensuse.org/project/show/network:messaging:zeromq:release-stable  or https://build.opensuse.org/project/show/network:messaging:zeromq:release-draft

I think it's not clear in the website what "latest git" means (I was expecting to found the builds of latest "master" branch) and what "latest stable release" means (I was expecting to find perhaps the builds of the latest released tags)...

@bluca can you clarify how OBS is configured so we can fix the website wording? thanks

**Comment by bluca** [comment]
why do you say 1r old or 2yr old?

**Comment by f18m** [comment]
> why do you say 1r old or 2yr old?

for example the "zeromq:git-stable" shows in the "changed" column the wording "over 1year ago":

![image](https://github.com/zeromq/zeromq.org/assets/9748595/3672f6c7-b814-4263-832b-d2b0abe7e0b5)

**Comment by bluca** [comment]
that's just the configuration of the build

**Comment by f18m** [comment]
> that's just the configuration of the build

ok my bad. It's just that the OBS UI is not... the best one I would say.
I built more trust on that when I checked e.g. this page https://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/Fedora_38/x86_64/

and there I see the date encoded in the RPM filename, e.g.

https://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/Fedora_38/x86_64/libzmq5-4.3.5+git20231110-1167.1.x86_64.rpm

I will try using these repos...

closing this ticket for now, thanks
