### ISSUE TITLE
The Guide isn't showing anymore

### ISSUE THREAD

**Issue by afonsolage** [zeromq/zeromq.org#80]
When I try to open http://zguide.zeromq.org/page:all it doesn't show the guide anymore. yesterday it was fine.

**Comment by somdoron** [comment]
Something changed with wikidot :(

I will try to file an issue

**Comment by sappo** [comment]
The failing Jenkins Job for the zguide could be the resson. I'll verify
this later.

Doron Somech <notifications@github.com> schrieb am So., 31. Mai 2020, 12:42:

> Something changed with wikidot :(
>
> I will try to file an issue
>

**Comment by sappo** [comment]
The upload worked fine now. It seems that the wikidot :all macro to show
all pages for a given tag is currently not working.

Am So., 31. Mai 2020 um 20:58 Uhr schrieb Kevin Sapper <
kevinsapper88@gmail.com>:

> The failing Jenkins Job for the zguide could be the resson. I'll verify
> this later.
>
> Doron Somech <notifications@github.com> schrieb am So., 31. Mai 2020,
> 12:42:
>
>> Something changed with wikidot :(
>>
>> I will try to file an issue
>>

**Comment by sappo** [comment]
It's not the all macro but the include macro that is no longer working.

I opened a bug in the support forum:
http://community.wikidot.com/forum/t-13398270/the-inline-macro-stopped-working

**Comment by somdoron** [comment]
An excuse to move it to gitbook or other alternatives?

**Comment by sappo** [comment]
Yes, but that involves converting the wikidot markup pages into markdown pages. Which is not an easy task.

**Comment by somdoron** [comment]
@sappo I think wikidot is now limiting the size of a page. the include macro does work, however it breaks at the fifth include. I suggest we convert it into links to chapters for now and try to convert the project to markdown for the long term.

**Comment by sappo** [comment]
I agree!

Am Mi., 3. Juni 2020 um 22:39 Uhr schrieb Doron Somech <
notifications@github.com>:

**Comment by sappo** [comment]
The `<page|java|hx|php|...>:all` pages are containing chapter links now.

**Comment by somdoron** [comment]
Thanks @sappo

**Comment by f18m** [comment]
@sappo , @bluca  I think this can be closed as well
