### ISSUE TITLE
Guide doesn't use HTTPS

### ISSUE THREAD

**Issue by rahulporuri** [zeromq/zeromq.org#92]
At the moment, I am unable to access https://zguide.zeromq.org/page:all. Trying to access the aforementioned URL on Firefox/Chrome lead me to the usual "Your connection isn't private"/other warning messages.

**Comment by rahulporuri** [comment]
Not really an issue as I am able to use the http URL but I still wanted to point this out as I couldn't find an issue regarding this.

**Comment by aagor** [comment]
This issue seems no longer existent. The guide can be used with HTTPS without problems.

**Comment by f18m** [comment]
I think this can be closed as well now...  cc @bluca
